### ISSUE TITLE
Option not to use/download root.hints

### ISSUE THREAD

**Issue by mrdima** [xaque208/puppet-unbound#103]
Having a purely caching forwarder which just forwards request to some other recursive nameserver there is no need for the root.hints file and in our case the servers can't even reach the Internet so it hangs on downloading the root.hints (until touching it manually). Please create an option not to use/download root.hints.

**Comment by xaque208** [comment]
Interesting use case.  I'll aim to take a look some time this week.

**Comment by mrdima** [comment]
Thanks, much appreciated
