### ISSUE TITLE
Default interfaces on multi-homed servers

### ISSUE THREAD

**Issue by nicwaller** [xaque208/puppet-unbound#12]
I ran into a strange problem today with Unbound while using this module. I'm not sure whether this is a configuration problem or a bug, so I'm reporting it here first.

On a server with two IP addresses, I had to explicitly list both IP addresses in unbound.conf before Unbound would answer queries on the second address. This ran counter to my expectation that I could set  `interface: 0.0.0.0` to listen on all IP addresses.

One possible solution is changing this module to explicitly list all IP addresses as listening interfaces in unbound.conf.

Before making that change, it would be prudent to:
- Confirm that this is 100% reproducible on a different system
- Ask the maintainers of Unbound (NLnet?) whether this behaviour is intended.

--
*The full story*

My server had Unbound installed and configured to listen on "0.0.0.0" interface. It was successfully responding to DNS queries for other hosts as defined by the `access-control` directive, even on different subnets.

Then I added a second IP address to the server as a virtual interface (`eth0:0`). Strangely, Unbound refused to answer DNS queries on this second IP address, even after restarting the service. Running netstat -tapn confirmed that Unbound was listening on `0.0.0.0:53`.

Then I explicitly listed each local IP address in `unbound.conf` and restarted Unbound. At that point, the server successfully responded to DNS queries as expected.

    interface: 192.168.0.20
    interface: 192.168.0.30

I'm using Scientific Linux 6.4, and the version of Unbound is 1.4.19 from EPEL.

**Comment by xaque208** [comment]
I believe this issue has been addressed by the inclusion of the `interface` param in `params.pp`.
