### ISSUE TITLE
Options not found

### ISSUE THREAD

**Issue by helmerfud** [xaque208/puppet-unbound#145]
hello,
i'm new user of your module and i did not find log-queries and log-replies options.
it's a security concern in my enterprise.
is it possible to add these options ?

thank you.

**Comment by xaque208** [comment]
Hi, thank you for the note.  Those options are absolutely welcome!  Is this something that you would be able to send a patch for?

**Comment by b4ldr** [comment]
this has been merged so can be closed now

**Comment by xaque208** [comment]
Thanks @b4ldr.
