### ISSUE TITLE
interface changes don't take affect

### ISSUE THREAD

**Issue by b4ldr** [xaque208/puppet-unbound#166]
If you change the `$interface` while you have `$control_enable` the interface change does not take affect.  This is because if control_enable is true the service refreshes using `unbound-control reload`.  however as per the documentation

> The  interfaces  are not changed on a reload (kill -HUP)  but only on restart. 

This means that any changes to the interfaces (even if it is the first run) do not take affect until a manual restart is preformed.  The simple fix would be to remove the offending block[1] however this would mean a full restart of the daemon for any config changes which may not be desirable.  A more hacky way would be to store the interfaces in a file and restart the service if that file changes.  something like

```puppet
file {"$confdir/interfaces.txt":
  ensure => file,
  notify  => Exec['etc/init/.d/unbound restart'],
  content => $interfaces.join('\n'),
}
exec {'/etc/init/.d/unbound restart':
  refreshonly => true,
}
 ```
what do you think?
[1]https://github.com/xaque208/puppet-unbound/blob/master/manifests/init.pp#L189-L192

**Comment by xaque208** [comment]
I believe this is complete.
