### ISSUE TITLE
service hasstatus => false

### ISSUE THREAD

**Issue by b4ldr** [xaque208/puppet-unbound#171]
I noticed that the [service statement](https://github.com/xaque208/puppet-unbound/blob/master/manifests/init.pp#L185) sets `hasstatus` to false.  I have checked ubuntu and freebsd and both seem to support status, do you remember why you turned this off?

**Comment by xaque208** [comment]
The commit from 2011 says `unbound does not have a status on debian`.  Perhaps that's changed since.  If so, then its probably safe to change.

**Comment by b4ldr** [comment]
created !175 this way it can be switched of if the failing version of debian is reported again

**Comment by xaque208** [comment]
#175 has been merged.
