### ISSUE TITLE
2.1.0 does not work with unbound version < 1.6.7

### ISSUE THREAD

**Issue by cruwe** [xaque208/puppet-unbound#172]
Could you consider please to have a patch-release 2.1.1 which includes 393d12bcb652e80a8046269a1ae691a7c9d5bb81? To have some control over possible breaking changes, I employ release-versions only and had 2.1.0 non-functional on Debian 9, which comes with unbound-1.6.0.

Thanks for your consideration (and of course for puppet-unbound)!

**Comment by xaque208** [comment]
Sure.  I'll look over recent commits for the changelog and push a release.

**Comment by xaque208** [comment]
`2.2.0` has been released for this.  The default value changes in the commit you references warrants an minor version bump.  Thank for hassling for a release.

**Comment by cruwe** [comment]
Thank you very much!
