### ISSUE TITLE
Unable to call unbound::local_zone class anymore

### ISSUE THREAD

**Issue by jlutran** [xaque208/puppet-unbound#177]
Since PR #153 unbound::local_zone class does not exists anymore.
Unfortunately, my puppet code was heavily using this feature to configure different local zones regarding of host type, eg :

```
ensure_resource('unbound::local_zone', '.', { 'type' => 'refuse' })
if( $zone1) { ensure_resource('unbound::local_zone', 'my.zone1.net', { 'type' => 'transparent' }) }
if( $zone2) { ensure_resource('unbound::local_zone', 'my.zone2.net', { 'type' => 'transparent' }) }
```

How can I use this feature again ? 
Merging all local zones a in single hash and pass it as a ::unbound class parameter seems kind of hard because of puppet immutable variable design

**Comment by jlutran** [comment]
I use unbound::local_zone as a resolver whitelist on my hosts :

1. Set resolver to localhost only
2. Disable all zones resolving ({ '.' => 'refuse' })
3. Add custom zones using multiple unbound::local_zone calls in separate puppet profiles

Your code above is working, but hard to implement in my case because `::unbound::local_zone` class is called from multiple puppet manifests.

**Comment by xaque208** [comment]
@b4ldr I assume then that the `unbound` class would then contain a `create_resources('unbound::local', $local_zone...)` or are you thinking something different?

@jlutran Would storing all of the local_zone data in the same hiera data object be enough for you?  I'm curious to learn more about why local_zone is in multiple manifests on the same node.  I assume just for organization purposes.  Is that right?

**Comment by b4ldr** [comment]
>@b4ldr I assume then that the unbound class would then contain a create_resources('unbound::local', $local_zone...) or are you thinking something different?

yes, it would mean going back to the old way of doing it.

**Comment by xaque208** [comment]
Bringing back the local_zone class while also supporting a parameter on the unbound class that, if defined, is passed to create_resources seems like the best of both worlds.  I'm speculating here, as I don't use the feature, but users would be able to define the resources centrally in hiera, or scattered throughout the manifest.

**Comment by jlutran** [comment]
> @jlutran Would storing all of the local_zone data in the same hiera data object be enough for you? I'm curious to learn more about why local_zone is in multiple manifests on the same node. I assume just for organization purposes. Is that right?

I use a default unbound profile, and then set some local zones on custom roles. For example : 

```
class profiles::unbound(
    $default_nameservers = hiera('public_nameservers', []),
    $proxy_endpoint = hiera('proxy', undef),
    $git_endpoint = hiera('git_source', undef),
) {
    unbound::forward { '.': address => $default_nameservers }
    ensure_resource('unbound::local_zone', '.', { 'type' => 'refuse' })
    ensure_resource('unbound::local_zone', $default_sync_server, { 'type' => 'transparent' })

    if( $proxy_endpoint ) {
        $proxy_domain = regsubst($proxy_endpoint, '^http[s]?://([^:/]+).*$', '\1')
        ensure_resource('unbound::local_zone', $proxy_domain, { 'type' => 'transparent' })
    }
    if( $git_endpoint ) {
        $git_domain = regsubst($git_endpoint, '^http[s]?://([^:/]+).*$', '\1')
        ensure_resource('unbound::local_zone', $git_domain, { 'type' => 'transparent' })
    }
}
```

```
class profiles::custom_role($metrics_endpoint) {
    ensure_resource('unbound::local_zone', $metrics_endpoint, { 'type' => 'transparent' })
}
```

And so on...

**Comment by xaque208** [comment]
#182 has been merged to resolve this.  Apologies for the trouble.
