### ISSUE TITLE
Wrong quoting for local-data TXT records

### ISSUE THREAD

**Issue by countsudoku** [xaque208/puppet-unbound#196]
Hi,

There is a problem with the qouting in the unbound.conf file for TXT records in the local-data field. Since TXT records can contain whitespaces double quotes are needed around the rdata part of the local-data set. Hence the local-data entry has to be single quoted. This is explicitly described in the unbound.conf man page:
> For record types such as TXT,  use  single  quotes,  as  in
>            local-data: 'example. TXT "text"'.

I would suggest to use single quotes for all local-data entries. This is not explicitly allowed in the unbound.conf manual, but it works on my unbound installation flawless.

Kind regards
Count Sudoku

**Comment by countsudoku** [comment]
Sorry, I was wrong! The quoting can be set by the caller for arrays.

**Comment by xaque208** [comment]
Not a worry, glad you sorted it out.

**Comment by FredericLespez** [comment]
I stumbled on the same problem and I don't understand what you were meaning by:
> The quoting can be set by the caller for arrays.

As far as I can see, the double quotes are hardcoded in the erb template:
https://github.com/voxpupuli/puppet-unbound/blob/e1b498d458004b2cabd6b163f0bcaea01e6bb55e/templates/local_zone.erb#L9

So how do you handle TXT records containing double quotes and spaces (like DKIM records) ?

Thanks in advance for your help.

**Comment by countsudoku** [comment]
My comment  above
> Sorry, I was wrong! The quoting can be set by the caller for arrays.

was for the `local-data` part in the [templates/unbound.conf.erb](https://github.com/voxpupuli/puppet-unbound/blob/e1b498d458004b2cabd6b163f0bcaea01e6bb55e/templates/unbound.conf.erb):
https://github.com/voxpupuli/puppet-unbound/blob/e1b498d458004b2cabd6b163f0bcaea01e6bb55e/templates/unbound.conf.erb#L192

If you hand over something like this:
```
$local_data = [
    "'mail._domainkey.example.com 14400 IN TXT \"v=DKIM1;h=sha256;k=rsa;\"\"p=DKIM_KEY_PART_1\"\"DKIM_KEY_PART_2\"'"
]
```
to the unbound class:
```
class { '::unbound':
    …,
    local_data => $local_data,
    …,
}
```
you will get, what you want.

For the quoting in [templates/local_zone.erb](https://github.com/voxpupuli/puppet-unbound/blob/e1b498d458004b2cabd6b163f0bcaea01e6bb55e/templates/local_zone.erb) you are absolutely right. So my comment above was right by accident:
> I would suggest to use single quotes for all local-data entries.

**Comment by FredericLespez** [comment]
Thanks a lot for your answer. I identified two ways to insert local-data (local_zone and record) but I missed the third one :-)
May be I will propose a pull request to automatically single quote TXT records and split them into pieces of 255 characters.
