### ISSUE TITLE
add ability to define/generate local-data + override local-zone template

### ISSUE THREAD

**Issue by findmyname666** [xaque208/puppet-unbound#215]
Hi there,
I would like to add functionality to generate local data for a zone by this unbound module.
Furthermore it would be cool to override a template for a local-zone e.g. i need to do additional stuff there.
I will create a PR for it.

**Comment by findmyname666** [comment]
PR created #216.

**Comment by findmyname666** [comment]
PR was merged into master - @xaque208 can we close it?

**Comment by xaque208** [comment]
Thanks for the note.  I've pushed `2.5.0` which includes the change above.
