### ISSUE TITLE
We should manage the permissions of /var/unbound/etc so that the root.key can be written by the unbound user.

### ISSUE THREAD

**Issue by xaque208** [xaque208/puppet-unbound#32]

**Comment by xaque208** [comment]
Has this issue been addressed?

**Comment by b4ldr** [comment]
you raised the issue shouldn't you be the one to confirm that or am i missing something???

**Comment by xaque208** [comment]
I just didn't see the PR you mentioned.  Thought I'd ask.

We set the owner here: https://github.com/xaque208/puppet-unbound/blob/master/manifests/init.pp#L111

This is good enough for now.

**Comment by b4ldr** [comment]
Oh yes that would have helped :)
