### ISSUE TITLE
Wrong unbound-checkconf path for Centos and Scientific 6

### ISSUE THREAD

**Issue by raiblue** [xaque208/puppet-unbound#99]
Hello,
It seems that path /sbin/unbound-checkconf does not fit neighter Centos nor Scientific linux (release 6), instead it is /usr/sbin/unbound-checkconf . Maybe you can fix this $validate_cmd value in params.pp?

**Comment by xaque208** [comment]
https://github.com/xaque208/puppet-unbound/pull/100

**Comment by xaque208** [comment]
Thank you for the report.
